# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [26]:
np.empty(10, order ='C')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [17]:
np.arange(10,50).shape

(40,)

5. Print the type of the previous array in question 3

In [16]:
np.arange(10,50).dtype

dtype('int32')

6. Print the numpy version and the configuration


In [98]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Reading/Softwares/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Reading/Softwares/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Reading/Softwares/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

7. Print the dimension of the array in question 3


In [99]:
np.arange(10,50).ndim

1

8. Create a boolean array with all the True values

In [32]:
np.full(5,True)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [46]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

10. Create a three dimensional array



In [47]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [51]:
a =np.arange(10,20)
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [53]:
null_array = np.empty(10)
null_array[4]=1
null_array

array([9.45259029e-312, 9.45259029e-312, 9.45259029e-312, 4.94065646e-324,
       1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 3.45845952e-323,
       0.00000000e+000, 0.00000000e+000])

13. Create a 3x3 identity matrix

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [70]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype('f')

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [71]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [72]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [86]:
odd = np.arange(10)
odd[(np.remainder(odd,2)!=0)]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [88]:
odd[(np.remainder(odd,2)!=0)]=-1
odd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [103]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [113]:
arr2 = np.ones((3,3))
arr2[(1,1)]= 0
arr2

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [115]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[(1,1)]= 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [116]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:] =64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[64, 64, 64],
        [64, 64, 64]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [120]:
arr2d1 = np.arange(9).reshape(3,3)
arr2d1[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [121]:
arr2d1 = np.arange(9).reshape(3,3)
arr2d1[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [122]:
arr2d1 = np.arange(9).reshape(3,3)
arr2d1[:2,2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [130]:
rd =np.random.randn(10,10)
np.max(rd)
np.min(rd)

-2.697759858520683

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [134]:
a = np.array([1,2,3,2,3,4,3,4,5,6]); b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [137]:
a = np.array([1,2,3,2,3,4,3,4,5,6]); b = np.array([7,2,10,2,7,4,9,4,9,8])
a==b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [140]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']); data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.39126502,  0.32104644, -0.18448912, -0.44454112],
       [-1.88119931,  0.22936995,  0.13087399, -0.15374341],
       [-1.64389895,  0.13546065,  1.28950584,  0.04353228],
       [ 0.299352  ,  0.69307595,  0.36381271,  0.37937319],
       [-0.36553097, -1.73798443,  1.22273086, -0.67088648]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [143]:
data[(names!='Will') & (names!='Joe')]

array([[ 0.39126502,  0.32104644, -0.18448912, -0.44454112],
       [-1.64389895,  0.13546065,  1.28950584,  0.04353228]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [145]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [150]:
a3d = np.arange(1,17).reshape(2,2,4)
a3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [151]:
a3d.reshape(4,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [171]:
a10 = np.arange(0,2,0.2)
print(a10)
asqrt = a10**0.5
print(asqrt)
asqrt[(asqrt)<0.5]=0 
asqrt


[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[0.         0.4472136  0.63245553 0.77459667 0.89442719 1.
 1.09544512 1.18321596 1.26491106 1.34164079]


array([0.        , 0.        , 0.63245553, 0.77459667, 0.89442719,
       1.        , 1.09544512, 1.18321596, 1.26491106, 1.34164079])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [177]:
rd1 =np.random.randn(12)
rd2 =np.random.randn(12)
np.where(rd1>rd2,rd1,rd2)

array([ 0.39481095, -0.47913415,  0.09348266, -0.03899021,  1.05710727,
       -0.09124066, -0.31611481,  0.7745259 ,  0.41481868,  0.33103222,
        0.47689514, -0.28845672])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [198]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq1 = np.unique(names)
np.sort(uniq1)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [221]:
a = np.array([1,2,3,4,5]); b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [207]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
sampleArray[:,1]=newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [217]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]); y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [212]:
rd3 =np.random.randn(20)
np.sum(rd3)

1.749099143907992