# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [12]:
a =np.arange(10).reshape(2,5)
b =np.ones(10).reshape(2,5)
np.vstack((a,b))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [13]:
a =np.arange(10).reshape(2,5)
b =np.ones(10).reshape(2,5)
np.hstack((a,b))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [17]:
a =np.arange(10).reshape(2,5)
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [19]:
a =np.arange(15).reshape(3,5)
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [21]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [23]:
np.arange(25).reshape(5,5)**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [26]:
m = np.arange(30).reshape(5,6)
np.mean(m,axis =0)


array([12., 13., 14., 15., 16., 17.])

## Question:9

### Find the standard deviation of the previous array in Q8?

In [27]:
np.std(m, axis =0)

array([8.48528137, 8.48528137, 8.48528137, 8.48528137, 8.48528137,
       8.48528137])

## Question:10

### Find the median of the previous array in Q8?

In [28]:
np.median(m, axis =0)

array([12., 13., 14., 15., 16., 17.])

## Question:11

### Find the transpose of the previous array in Q8?

In [31]:
m.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [44]:
s =np.arange(1,17).reshape(4,4)
np.trace(s)

34

## Question:13

### Find the determinant of the previous array in Q12?

In [45]:
np.linalg.det(s)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [48]:
np.percentile(s,5)
np.percentile(s,95)

15.25

## Question:15

### How to find if a given array has any null values?

In [46]:
np.isnan(s)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])